pipeline {
    agent {
        kubernetes {
            yamlFile 'K8sPod.yaml'
        }
    }

    environment {
        CI = "false"
        DINGTALK_URL = "$DINGTALK_WEBHOOK"
        DOCKER_REPO = "$IMAGE_REPOSITORY"
        OWNER_PHONE = "$PHONE"
    }

    options {
        disableConcurrentBuilds()
    }


    stages {
        stage('prepare') {
            steps {
                sh '''
                  curl -d '{"msgtype": "text","text": {"content":"'"$JOB_NAME"': 开始打包应用与构建镜像'"$BUILD_URL"'"}}' -H 'Content-Type: application/json'  "$DINGTALK_URL"
                '''
                script {
                    env.IMAGE_TAG = ""
                }
            }
        }

        stage('pre-build') {

            when {
                anyOf {
                    branch 'dev'
                    branch 'release'
                    branch 'master'
                }
            }

            steps {
                container('node') {
                    sh "printenv"
                    // sh './jenkins/pre-build.sh'
                    sh '''
                        yarn -v

                        if [ $? -eq 0 ];then
                            echo 'exist yarn'
                        else
                            echo 'not exist yarn'
                            npm install -g yarn
                        fi
                    '''
                    sh "yarn config set registry https://registry.npmmirror.com"
                    sh "yarn install"
                }
            }
        }

        stage('build-Parallel') {

            when {
                anyOf {
                    branch 'dev'
                    branch 'release'
                    branch 'master'
                }
            }
            failFast false

            parallel {

                stage('build-test') {
                    when {
                        beforeAgent true
                        branch 'dev'
                    }

                    steps {
                        container('node') {
                            echo "build-test"
                            sh "yarn build"
                        }
                    }
                }

                stage('build-uat') {

                    when {
                        beforeAgent true
                        branch 'release'
                    }

                    steps {
                        container('node') {
                            echo "build-uat"
                            sh "yarn build"
                        }
                    }
                }

                stage('build-prod') {

                    when {
                        beforeAgent true
                        branch 'master'
                    }

                    steps {
                        container('node') {
                            echo "build-prod"
                            sh "yarn build"
                        }
                    }
                }
            }
        }

        stage("artifacts-manage"){
            steps {
                sh '''
                    curl -d '{"msgtype": "text","text": {"content":"'"$JOB_NAME"': 应用打包成功，开始构建镜像..."}}' -H 'Content-Type: application/json' "$DINGTALK_URL"
                '''
                container('docker') {
                    echo "artifacts"
                    // cat nginx.sh => envsubst '$ENV_NAME' < "nginx.$GIT_BRANCH.template" > nginx.conf
                    // 复杂切换不同环境的配置文件，适合于需要把环境变量注入配置文件内的业务场景
                    // docker run --privileged -e ENV_NAME=$ENV_NAME -e GIT_BRANCH=$GIT_BRANCH -v root_jenkins:/kr bhgedigital/envsubst sh -c "cd /kr/workspace/whitelist-fe_dev/conf && sh nginx.sh"
                    // 简单切换不同环境的配置文件，适合不需要用到环境变量的业务场景
                    // cp "./conf/nginx.$GIT_BRANCH.template" ./conf/nginx.conf
                    script {
                        sh '''
                          echo "${ALI_DOCKER_HUB_HOST}/${DOCKER_REPO}:${GIT_BRANCH}-${GIT_COMMIT:0:8}-$(date "+%Y%m%d%H%M%S")" > temp.txt
                        '''
                        env.IMAGE_TAG = readFile('temp.txt').trim()
                    }

                    sh '''
                        rm -f ./conf/nginx.conf
                        cp "./conf/nginx.$GIT_BRANCH.template" ./conf/nginx.conf
                        cat ./conf/nginx.conf
                        docker build -t ${IMAGE_TAG}  . || exit 1
                        docker login ${ALI_DOCKER_HUB_HOST} -u ${ALI_DOCKER_HUB_USER} -p ${ALI_DOCKER_HUB_PWD} || exit 1
                        docker push ${IMAGE_TAG} || exit 1
                    '''
                }
                sh '''
                    curl -d '{"msgtype": "text","text": {"content":"'"$JOB_NAME"': 镜像构建成功'"$IMAGE_TAG"'，已推送至镜像仓库"}, "at": { "atMobiles": ["'"$OWNER_PHONE"'"] }}' -H 'Content-Type: application/json' "$DINGTALK_URL"
                '''
            }
        }
    }

    post {

        changed{
            echo 'I changed!'
        }

        failure{
            echo 'I failed!'
            sh '''
              curl -d '{"msgtype": "text","text": {"content":"'"$JOB_NAME"': 打包/构建失败"}, "at": { "atMobiles": ["'"$OWNER_PHONE"'"] }}' -H 'Content-Type: application/json' "$DINGTALK_URL"
            '''
        }

        success{
            echo 'I success'
            // sh '''
            //   curl -d '{"msgtype": "text","text": {"content":"'"$JOB_NAME"': 构建结束"}}' -H 'Content-Type: application/json' "$DINGTALK_URL"
            // '''
        }

        always{
            echo 'I always'
         }

        unstable{
            echo "unstable"
        }
        aborted{
            echo "aborted"
        }
    }

}