apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
  namespace: jenkins
spec:
  containers:
  - image: jenkins/inbound-agent:4.3-4-jdk11
    imagePullPolicy: IfNotPresent
    name: jnlp
    volumeMounts:
    - mountPath: /home/jenkins/agent
      name: workspace-volume
    workingDir: /home/jenkins/agent
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
  - args:
    - "9999999"
    command:
    - sleep
    image: docker:19.03-git
    imagePullPolicy: IfNotPresent
    name: docker
    volumeMounts:
    - mountPath: /run/docker.sock
      name: volume-1
    - mountPath: /home/jenkins/agent
      name: workspace-volume
    workingDir: /home/jenkins/agent
  volumes:
  - name: volume-1
    hostPath:
      path: /run/docker.sock
      type: ""
  - name: workspace-volume
    emptyDir: {}