apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
  namespace: jenkins
spec:
  containers:
  - image: jenkins/inbound-agent:4.3-4-jdk11
    imagePullPolicy: IfNotPresent
    name: jnlp
    volumeMounts:
    - mountPath: /home/jenkins/agent
      name: workspace-volume
    workingDir: /home/jenkins/agent
    resources:
      requests:
        cpu: 1000m
        memory: 384Mi
  - args:
    - "9999999"
    command:
    - sleep
    image: maven:3.6-openjdk-8-slim
    imagePullPolicy: IfNotPresent
    name: maven
    volumeMounts:
    - mountPath: /root/.m2
      name: volume-0
    - mountPath: /run/docker.sock
      name: volume-1
    - mountPath: /home/jenkins/agent
      name: workspace-volume
    - mountPath: /home/jenkins/settings
      name: config-volume
    env:
      - name: MAVEN_SETTINGS_PATH
        valueFrom:
          configMapKeyRef:
            name: maven-settings
            key: maven-settings-file-path
      - name: MAVEN_SETTINGS
        value: "/home/jenkins/settings/$(MAVEN_SETTINGS_PATH)"
    workingDir: /home/jenkins/agent
  - args:
    - "9999999"
    command:
    - sleep
    image: docker:19.03-git
    imagePullPolicy: IfNotPresent
    name: docker
    volumeMounts:
    - mountPath: /root/.m2
      name: volume-0
    - mountPath: /run/docker.sock
      name: volume-1
    - mountPath: /home/jenkins/agent
      name: workspace-volume
    workingDir: /home/jenkins/agent
  volumes:
  - name: volume-0
    persistentVolumeClaim:
      claimName: cce-efs-import-maven-cache
  - name: volume-1
    hostPath:
      path: /run/docker.sock
      type: ""
  - name: workspace-volume
    emptyDir: {}
  - name: config-volume
    configMap:
      name: maven-settings